language: python
sudo: required
dist: xenial
python: "3.7"
services: postgresql
env:
  - DJANGO_VERSION=2.1.1
cache: pip
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test duels
