language: python
os:
  - linux
python:
  - '3.7'
services: postgresql
env:
  - DJANGO_VERSION=2.1.1
cache: pip
install:
  - pip install requirements.txt
script:

  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test myApp
